#conf
[App]
    DebugMode="debug"
    TimeLocation="Asia/Chongqing"

[Server]
    HTTPPort = ":9090"

[Log]
    FileName = "log/zap.log"
    MaxSize = 100
    LocalTime = true
    Compress = true

[Mysql]
    UserName = "root"
    PassWord = "admin888"
    IPHost = "127.0.0.1"
    Port = "3306"
    DbName = "go_test"
    TablePrefix = "blog_"
    MaxIdleConns = 25 #设置空闲链接
    MaxOpenConns = 25  # 最大连接数 0为不限制
    ConnMaxLifetime = 60 #可重用链接得最大时间长度，单位分钟

[Redis]
    IPHost = "127.0.0.1:6379"